# Generated by Django 5.2.4 on 2025-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('booked', 'Booked'), ('refund_pending', 'Refund Pending'), ('refund', 'Refund'), ('available', 'Available')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('booked', 'Booked'), ('refund_pending', 'Refund Pending'), ('refund', 'Refund'), ('available', 'Available')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxibooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('booked', 'Booked'), ('refund_pending', 'Refund Pending'), ('refund', 'Refund'), ('available', 'Available')], default='Booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('booked', 'Booked'), ('refund_pending', 'Refund Pending'), ('refund', 'Refund'), ('available', 'Available')], default='Approved', max_length=20),
        ),
    ]
