# Generated by Django 5.2.4 on 2025-09-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_booking_status_alter_taxi_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='linked_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_hotel_bookings', to='user.booking'),
        ),
        migrations.AddField(
            model_name='taxibooking',
            name='linked_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_taxi_bookings', to='user.booking'),
        ),
    ]
