# Generated by Django 5.2.4 on 2025-09-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_hotel_linked_booking_taxibooking_linked_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
