# Generated by Django 5.2.4 on 2025-09-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='linked_booking',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='linked_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_hotel_bookings', to='user.booking'),
        ),
    ]
