# Generated by Django 5.2.4 on 2025-09-08 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_hotel_linked_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='linked_booking',
        ),
        migrations.RemoveField(
            model_name='taxibooking',
            name='linked_booking',
        ),
    ]
